---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-luojun96-io-v1beta1-customdeamonset
  failurePolicy: Fail
  name: mcustomdeamonset.kb.io
  rules:
  - apiGroups:
    - apps.luojun96.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customdeamonsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-luojun96-io-v1beta1-customdeamonset
  failurePolicy: Fail
  name: vcustomdeamonset.kb.io
  rules:
  - apiGroups:
    - apps.luojun96.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customdeamonsets
  sideEffects: None
