# permissions for end users to view customdeamonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customdeamonset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator-opt
    app.kubernetes.io/part-of: k8s-operator-opt
    app.kubernetes.io/managed-by: kustomize
  name: customdeamonset-viewer-role
rules:
- apiGroups:
  - apps.luojun96.io
  resources:
  - customdeamonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.luojun96.io
  resources:
  - customdeamonsets/status
  verbs:
  - get
