---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.luojun96.io
  resources:
  - customdeamonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.luojun96.io
  resources:
  - customdeamonsets/finalizers
  verbs:
  - update
- apiGroups:
  - apps.luojun96.io
  resources:
  - customdeamonsets/status
  verbs:
  - get
  - patch
  - update
